### ISSUE TITLE
GridView (table) with rounded corners?

### ISSUE THREAD

**Issue by JosefPihrt** [riganti/dotvvm#1432]
Hi,

It is possible to configure GridView so it has rounded corners?

So far I found a solution that works but requires a block of CSS code.

```css
table.dotvvm-bp-primitive_table {
    border-spacing: 0;
    border-collapse: separate !important;
    border-radius: 4px;
}

    table.dotvvm-bp-primitive_table th,
    table.dotvvm-bp-primitive_table td {
        border: none;
    }

        table.dotvvm-bp-primitive_table th:not(:last-child),
        table.dotvvm-bp-primitive_table td:not(:last-child) {
            border-right: var(--bp-border-width) solid var(--bp-border-color);
        }

    table.dotvvm-bp-primitive_table > thead > tr > th,
    table.dotvvm-bp-primitive_table > thead > tr:not(:last-child) > td,
    table.dotvvm-bp-primitive_table > tbody > tr:not(:last-child) > th,
    table.dotvvm-bp-primitive_table > tbody > tr:not(:last-child) > td,
    table.dotvvm-bp-primitive_table > tfoot > tr:not(:last-child) > th,
    table.dotvvm-bp-primitive_table > tfoot > tr:not(:last-child) > td,
    table.dotvvm-bp-primitive_table > tr:not(:last-child) > td,
    table.dotvvm-bp-primitive_table > tr:not(:last-child) > th,
    table.dotvvm-bp-primitive_table > thead:not(:last-child),
    table.dotvvm-bp-primitive_table > tbody:not(:last-child),
    table.dotvvm-bp-primitive_table > tfoot:not(:last-child) {
        border-bottom: var(--bp-border-width) solid var(--bp-border-color);
    }
```

If it not possible, I can make a suggestion to add this functionality in a future?
