### ISSUE TITLE
resource pathing behind nginix ingress

### ISSUE THREAD

**Issue by dleonardNetalytics** [riganti/dotvvm#1649]
We're attempting to run a dotvvm site in Kubernetes behind a Nginx ingress.

while everything works locally, even if run from a docker container, when running behind the ingress we're seeing issues where the site wont load.

its specifically failing trying to find a 'dotvvm--internal' script at the (example) url
https://myCoolURLhere.com/dotvvmResource/jUwMRn0laxpYA4BX1REy/dotvvm--internal
behind the ingress the path should be
https://myCoolURLhere.com/assessments/dotvvmResource/jUwMRn0laxpYA4BX1REy/dotvvm--internal

We were originally also having problems getting bootstrap and our css to load,
changing from the following

`config.Resources.Register("bootstrap-css", new StylesheetResource()
{
    Location = new UrlResourceLocation("~/Content/bootstrap.min.css")
});`
to
`config.Resources.Register("bootstrap-css", new StylesheetResource()
{
    Location = new UrlResourceLocation("./Content/bootstrap.min.css")
});`

fixes the pathing to bootstrap, and the css files when behind the ingress.

Is there a property or configuration setting I can adjust so that it looks for the dotvvm--internal script with the appropriate ingress path included ?

Thanks.

**Comment by dleonardNetalytics** [comment]
Thank you for the response,

 I tried what you suggested and set the path base when running behind the ingress.
i also made sure that UsePathBase is being applied before the call to app.UseRouting as described in the msdn article.

` if (Configuration["Assessments:IngressPath"].Length > 0)
  {
        logger.LogCritical($"SETTING PathBase to {Configuration["Assessments:IngressPath"]}");
        app.UsePathBase(Configuration["Assessments:IngressPath"]);
  }

  app.UseRouting();
`
I can tell that the call to UsePathBase is happening when running in kube because I can see my log entries being written.

'crit: Netalytics.Assessments.Frontend.Startup[0]
      SETTING PathBase to /assessments
'
Unfortunately, when I go to the page it's still looking for the dotvvm--internal script without taking the path into account.
Its like UsePathBase didnt really affect it.

**Comment by tomasherceg** [comment]
Thanks for the info, I'll try to reproduce it on my cluster.

**Comment by tomasherceg** [comment]
I was able to get it running with a combination of ingress (without rewriting) and `UsePathBase`:

ingress.yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetesvirtualdirectorytest-ingress
  labels:
    service: kubernetesvirtualdirectorytest
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "kubernetesvirtualdirectorytest.updatedays.cz"
    http:
      paths:
      - path: /sub-app
        pathType: Prefix
        backend:
          service:
            name: kubernetesvirtualdirectorytest
            port: 
              number: 80
```

Startup.cs
```
...
app.UsePathBase("/sub-app");
app.UseRouting();
...
```

Are you using rewrite rule on the ingress to remove the `/assessments` segment? I think this would be the problem - the app needs to know it is running in a virtual directory so it would generate the URLs correctly.
